/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1.2-5-g8f77695e65-20251016"
#endif /* AVUTIL_FFVERSION_H */
